# Generated by Django 5.2 on 2026-01-22 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_language_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="data_of_death",
            new_name="date_of_death",
        ),
    ]
