# Generated by Django 6.0.1 on 2026-02-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("Can_mark_returned", "Set book as returned"),),
            },
        ),
    ]
